version: "3.8"
services:
  database:
    image: postgres
    container_name: database
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/migration_master.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./db/seed_master.sql:/docker-entrypoint-initdb.d/seed.sql
  server:
    image: hopcamp/server
    container_name: server
    restart: unless-stopped
    build: ./server
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      PORT: 80
    depends_on:
      - database
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./server:/code/src
    command: npm start
  client:
    image: hopcamp/client
    container_name: client
    restart: unless-stopped
    build: ./client
    depends_on:
      - server
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/code/src
    command: npm start
volumes:
  pg-data:
