version: "3"
services:
  database:
    image: postgres
    container_name: hopcamp-db
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/migration_master.sql:/docker-entrypoint-initdb.d/migration.sql
      - ./db/seed_master.sql:/docker-entrypoint-initdb.d/seed.sql
  server:
    image: hopcamp/server
    container_name: hopcamp-api
    restart: unless-stopped
    build: ./server
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}
      PORT: 80
    depends_on:
      - hopcamp-db
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./server/src:/code/src
    command: npm start
  client:
    image: hopcamp/client
    container_name: hopcamp-app
    restart: unless-stopped
    build: ./client
    environment:
      API_URL: http://hopcamp-api
      PORT: ${CLIENT_PORT}
    depends_on:
      - hopcamp-api
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/code/src
    command: npm start
volumes:
  pg-data:
